mcpServers:
  example-server:
    type: stdio
    command: node
    args:
      - example/simple_server.js

  spotify-profile:
    type: stdio
    command: node
    args:
      - example/spotify/profile.js